import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Header";
import { Providers } from "./Providers";
import MessageModal from "./components/modals/MessageModal";
import SocketAndCalls from "./components/layout/SocketAndCalling";
import { QueryClient} from "@tanstack/react-query";
import QueryErrorHandler from "./components/layout/QueryErrorHandler";
import { ApiProvider } from "./components/layout/ApiProvider";
import Footer from "./components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} antialiased font-merriweather`}
      >
        <Providers>
          <ApiProvider>
            <QueryErrorHandler>
              <SocketAndCalls />
              <MessageModal />
              <Navbar />
              {children}
              <Footer />
            </QueryErrorHandler>
          </ApiProvider>
        </Providers>
      </body>
    </html>
  );
}
